name: Daily Learning Note Generator

on:
  schedule:
    # Run every day at 9 AM UTC (6 AM BRT)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  generate-learning-note:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get current date
        id: date
        run: |
          echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "day_name=$(date +'%A')" >> $GITHUB_OUTPUT
          echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT

      - name: Generate learning topic with Claude
        id: generate
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Define learning topics
          TOPICS=(
            "React-Server-Components-patterns"
            "TypeScript-advanced-types"
            "Next.js-performance-optimization"
            "Testing-best-practices"
            "Monorepo-architecture-patterns"
            "CSS-and-Tailwind-techniques"
            "JavaScript-ES2024-features"
            "Git-workflows-and-collaboration"
            "API-design-principles"
            "Database-optimization"
            "Security-best-practices"
            "Accessibility-standards"
            "State-management-patterns"
            "Build-tools-and-bundlers"
            "CI-CD-strategies"
          )

          # Select random topic
          RANDOM_TOPIC="${TOPICS[$RANDOM % ${#TOPICS[@]}]}"
          # Convert to title case for filename (e.g., "React Server Components Patterns")
          TOPIC_TITLE=$(echo "$RANDOM_TOPIC" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1')
          echo "Selected topic: $RANDOM_TOPIC"
          echo "topic=$RANDOM_TOPIC" >> $GITHUB_OUTPUT
          echo "topic_title=$TOPIC_TITLE" >> $GITHUB_OUTPUT

          # Create prompt
          cat > prompt.txt << 'PROMPT_END'
          You are creating a daily learning note for a software engineer at Cloudwalk working on InfinitePay.

          Create a concise but informative learning note (200-300 words) that:
          1. Explains a key concept or pattern
          2. Provides a practical example relevant to Next.js/React/TypeScript
          3. Includes actionable tips or best practices
          4. Suggests one resource for deeper learning

          IMPORTANT: Format the response EXACTLY like this example, with proper YAML frontmatter:

          ---
          created: YYYY-MM-DD
          tags: [learning, doc, programming]
          ---

          # Topic Title

          Your content here...

          Use the #learning, #doc, and #programming tags, and add 1-2 more specific tags if relevant (like #react, #typescript, #nextjs, #testing, etc).
          PROMPT_END

          # Call Claude API
          RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -d @- << EOF
          {
            "model": "claude-3-5-sonnet-20241022",
            "max_tokens": 2048,
            "messages": [{
              "role": "user",
              "content": "$(cat prompt.txt)\n\nTopic: ${RANDOM_TOPIC//-/ }\nDate: ${{ steps.date.outputs.today }}"
            }]
          }
          EOF
          )

          # Extract content
          CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text')

          if [ -z "$CONTENT" ] || [ "$CONTENT" = "null" ]; then
            echo "Error: Failed to generate content"
            echo "$RESPONSE"
            exit 1
          fi

          # Create filename following the pattern of existing notes
          FILENAME="00-Inbox/${TOPIC_TITLE}.md"

          # Check if file already exists
          if [ -f "$FILENAME" ]; then
            echo "Note already exists: $FILENAME"
            echo "Skipping creation to avoid overwriting existing notes"
            echo "filename=" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Write file
          echo "$CONTENT" > "$FILENAME"

          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Check if note was created
        run: |
          if [ -z "${{ steps.generate.outputs.filename }}" ]; then
            echo "Note already exists, skipped creation"
            exit 0
          fi

          if [ ! -f "${{ steps.generate.outputs.filename }}" ]; then
            echo "Error: Note file was not created"
            exit 1
          fi

          echo "Successfully created: ${{ steps.generate.outputs.filename }}"
          echo "Content preview:"
          head -20 "${{ steps.generate.outputs.filename }}"

      - name: Commit and push to main
        if: steps.generate.outputs.filename != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add "${{ steps.generate.outputs.filename }}"
          git commit -m "Add daily learning note: ${{ steps.generate.outputs.topic_title }}

          Generated learning note for ${{ steps.date.outputs.day_name }}, ${{ steps.date.outputs.today }}

          🤖 Generated with Claude via GitHub Actions"

          git push origin main

      - name: Workflow summary
        run: |
          echo "## 📚 Daily Learning Note Generated!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** ${{ steps.date.outputs.today }}" >> $GITHUB_STEP_SUMMARY
          echo "**Topic:** ${{ steps.generate.outputs.topic_title }}" >> $GITHUB_STEP_SUMMARY
          echo "**File:** ${{ steps.generate.outputs.filename }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -z "${{ steps.generate.outputs.filename }}" ]; then
            echo "Note already exists - no changes made." >> $GITHUB_STEP_SUMMARY
          else
            echo "Note has been committed and pushed to main branch." >> $GITHUB_STEP_SUMMARY
          fi
